### ISSUE TITLE
Wins count negative

### ISSUE THREAD

**Issue by wrigley826** [Hydrosaur/electrosmod#1]
I've now had three matches where I won but got negative points. This is the most recent one: https://tagpro.eu/?match=2278486

**Comment by wrigley826** [comment]
Just happened again: https://tagpro.eu/?match=2278726

**Comment by Hydrosaur** [comment]
Ok, I'm looking into it.

**Comment by JerryDot** [comment]
Here's a couple of instances I ran into:
https://tagpro.eu/?match=2279211
https://tagpro.eu/?match=2279333

Maybe it is related to the fact that we joined a game in progress for each of these?

**Comment by Hydrosaur** [comment]
I found the issue and it's been fixed. Joining a game in progress wasn't the direct cause of the problem but may have created a domino effect into this bug.
