### ISSUE TITLE
High refresh rate display causing frame drops

### ISSUE THREAD

**Issue by ParretLabs** [Hydrosaur/electrosmod#2]
Yeah, there are no details on this. I guess.

**Comment by ParretLabs** [comment]
This just in, BREAKING NEWS: Very choppy play

**Comment by RonSpawnson** [comment]
After further testing, this is not very reproducible. Profiling also doesn't suggest any issue with the extension as being related. Chalk this up to some other outside factor. Feel free to close :D

**Comment by Hydrosaur** [comment]
oh i forgot to close
